# Generated by Django 2.2.4 on 2019-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=300)),
                ('place1', models.CharField(max_length=300)),
                ('place2', models.CharField(max_length=300)),
                ('place_url', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=300)),
                ('place1', models.CharField(max_length=300)),
                ('place2', models.CharField(max_length=300)),
                ('place_url', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=300)),
                ('place1', models.CharField(max_length=300)),
                ('place2', models.CharField(max_length=300)),
                ('place_url', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Musical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=300)),
                ('place1', models.CharField(max_length=300)),
                ('place2', models.CharField(max_length=300)),
                ('place_url', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
