# Generated by Django 2.1.7 on 2019-08-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('tel', models.CharField(max_length=300)),
                ('place1', models.CharField(max_length=300)),
                ('place2', models.CharField(max_length=300)),
                ('place_url', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Category')),
            ],
        ),
    ]
