# Generated by Django 2.1.7 on 2019-08-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_comment_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
    ]
